export const endpoints = {
  getTickers: "/api/getTickers",
  getMarketSummary: "/api/getMarketSummary",
  getTickerData: "/api/getTickerData",
  getTickerSummary: "/api/getTickerSummary",
  getCompanyOverview: "/api/getCompanyOverview",
  getStockMarketNews: "/api/getStockMarketNews",
  getGeneralMarketNews: "/api/getGeneralMarketNews",
  createProfile: "/api/auth/create-profile",
  fetchProfile: "api/auth/fetch-profile",
  getBiggestGainers: "/api/getBiggestGainers",
  getBiggestLosers: "/api/getBiggestLosers",
  getMostActive: "/api/getMostActive",
  getWatchlist: "/api/getWatchlist",
  addToWatchlist: "/api/addToWatchlist",
};